### ISSUE TITLE
Cannot run on neo4j 3.1.0

### ISSUE THREAD

**Issue by simoncalabrese** [buschmais/extended-objects#170]
Exception in thread "main" java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /Users/simon/Documents/FileNeo4J
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:160)
	at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:43)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:110)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:129)
	at org.neo4j.graphdb.factory.GraphDatabaseFactory$1.newDatabase(GraphDatabaseFactory.java:117)
	at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:185)
	at com.buschmais.xo.neo4j.api.FileDatastoreFactory.createGraphDatabaseService(FileDatastoreFactory.java:31)
	at com.buschmais.xo.neo4j.api.FileDatastoreFactory.createGraphDatabaseService(FileDatastoreFactory.java:16)
	at com.buschmais.xo.neo4j.api.Neo4jXOProvider.createDatastore(Neo4jXOProvider.java:24)
	at com.buschmais.xo.impl.XOManagerFactoryImpl.<init>(XOManagerFactoryImpl.java:51)
	at com.buschmais.xo.impl.bootstrap.XOBootstrapServiceImpl.createXOManagerFactory(XOBootstrapServiceImpl.java:36)
	at com.buschmais.xo.impl.bootstrap.XOBootstrapServiceImpl.createXOManagerFactory(XOBootstrapServiceImpl.java:31)
	at com.buschmais.xo.api.bootstrap.XO.createXOManagerFactory(XO.java:26)
	at dao.EmployeeDao.main(EmployeeDao.java:19)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.NeoStoreDataSource@259d06d7' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:462)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:112)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:156)
	... 13 more
Caused by: org.neo4j.kernel.impl.storemigration.UpgradeNotAllowedByConfigurationException: Failed to start Neo4j with an older data store version. To enable automatic upgrade, please set configuration parameter "allow_store_upgrade=true"
	at org.neo4j.kernel.impl.storemigration.ConfigMapUpgradeConfiguration.checkConfigurationAllowsAutomaticUpgrade(ConfigMapUpgradeConfiguration.java:39)
	at org.neo4j.kernel.impl.storemigration.StoreUpgrader.migrateIfNeeded(StoreUpgrader.java:135)
	at org.neo4j.kernel.NeoStoreDataSource.upgradeStore(NeoStoreDataSource.java:664)
	at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:538)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 18 more

**Comment by simoncalabrese** [comment]
Sorry, can I have suggestions about this error? thank you and good work.

**Comment by DirkMahler** [comment]
Can you describe what you did? The message indicates that you're trying to start on an older database version (2.x)?

**Comment by simoncalabrese** [comment]
I read it but my neo4j server is 3.1.0

**Comment by simoncalabrese** [comment]
https://github.com/simoncalabrese/Spider-network.git here you can read what i put in my maven project

**Comment by DirkMahler** [comment]
Had a look at it:

1. XO 0.7.0 does not support Neo4j 3.x, the latest snapshot (0.8.0-SNAPSHOT) does. So either use XO 0.7.0/Neo4j 2.3.x or XO 0.8.0-SNAPSHOT/Neo4j 3.1.0.
2. The error message you reported indicates that Neo4j is starting up but the database has been created with an older version (probably 2.x) and migration is not enabled. Just delete the existing directory and retry, it should work.

In your code (DAO) you need to use transactions, i.e.

```
xo.currentTransaction.begin();
....
xo.currentTransaction.commit();
```
