### ISSUE TITLE
Neo4j v5 Support

### ISSUE THREAD

**Issue by JohT** [buschmais/extended-objects#180]
Hi,

first of all, thanks 👏 for all the great tools you provide. I've built a fully automated [Code Graph Analysis Pipeline](https://github.com/JohT/code-graph-analysis-pipeline) using [jQAssistant](https://jqassistant.org) and [Neo4j](https://neo4j.com/) that wouldn't be possible without these cool libraries.

### Used Versions

- jqassistant-commandline-neo4jv3-1.12.2
   - com.buschmais.xo-xo.neo4j.*-1.4.2
- neo4j-community-5.9.0 (no problem with neo4j-community-4.4.20)

### Current Behavior

When I use jQAssistant with a separately installed Neo4j v5 I get the following exception. 

```
Exception in thread "main" com.buschmais.xo.api.XOException: Cannot execute statement 'CALL db.indexes() YIELD tokenNames AS labels, properties AS properties RETURN labels, properties', {}
        at com.buschmais.xo.neo4j.remote.impl.datastore.StatementExecutor.execute(StatementExecutor.java:51)
        at com.buschmais.xo.neo4j.remote.impl.datastore.RemoteCypherQuery.execute(RemoteCypherQuery.java:36)
        at com.buschmais.xo.neo4j.spi.AbstractNeo4jDatastoreSession.getIndexes(AbstractNeo4jDatastoreSession.java:70)
        at com.buschmais.xo.neo4j.spi.AbstractNeo4jDatastoreSession.getIndexes(AbstractNeo4jDatastoreSession.java:30)
        at com.buschmais.xo.neo4j.spi.AbstractNeo4jDatastore.lambda$init$2(AbstractNeo4jDatastore.java:40)
        at com.buschmais.xo.neo4j.spi.AbstractNeo4jDatastore.inTransaction(AbstractNeo4jDatastore.java:57)
        at com.buschmais.xo.neo4j.spi.AbstractNeo4jDatastore.init(AbstractNeo4jDatastore.java:40)
        at com.buschmais.xo.impl.XOManagerFactoryImpl.<init>(XOManagerFactoryImpl.java:57)
        at com.buschmais.xo.impl.bootstrap.XOBootstrapServiceImpl.createXOManagerFactory(XOBootstrapServiceImpl.java:41)
        at com.buschmais.xo.api.bootstrap.XO.createXOManagerFactory(XO.java:48)
        at com.buschmais.jqassistant.core.store.impl.AbstractGraphStore.start(AbstractGraphStore.java:66)
        at com.buschmais.jqassistant.commandline.task.AbstractStoreTask.withStore(AbstractStoreTask.java:69)
        at com.buschmais.jqassistant.commandline.task.AnalyzeTask.run(AnalyzeTask.java:65)
        at com.buschmais.jqassistant.commandline.Main.executeTask(Main.java:306)
        at com.buschmais.jqassistant.commandline.Main.executeTasks(Main.java:264)
        at com.buschmais.jqassistant.commandline.Main.interpretCommandLine(Main.java:247)
        at com.buschmais.jqassistant.commandline.Main.run(Main.java:93)
        at com.buschmais.jqassistant.commandline.Main.main(Main.java:64)
Caused by: org.neo4j.driver.exceptions.ClientException: There is no procedure with the name `db.indexes` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
        at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:144)
        at org.neo4j.driver.internal.InternalTransaction.run(InternalTransaction.java:60)
        at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:37)
        at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:43)
        at com.buschmais.xo.neo4j.remote.impl.datastore.StatementExecutor.execute(StatementExecutor.java:49)
...
```

### Wanted Behavior

It would be great to be able to also use Neo4j v5 to stay up to date and use the newest features, although Neo4j v4.4 has currently long term support (LTS).

### Questions

- It seems that this has already been addressed in commit [upgraded initial Neo4j queries to support 5.x](https://github.com/buschmais/extended-objects/commit/bd484e283f44a26c250cd80d5108516fa8ca98d0). When will the upcoming version 2.2.0 be released?
- Are there plans to update jqassistant-commandline to that?
- Or are there any known workarounds I could try?

Best regards, [Johannes](https://github.com/JohT)

**Comment by DirkMahler** [comment]
This issue has already been adressed. We're currenty preparing the official release of jQA 2.0 which comes with Neo4j 4.x and supporting Neo4j 5.x for remote connections (thus integrating the mentioned fix in XO). The CLI distribution is available via Maven Central: https://repo1.maven.org/maven2/com/buschmais/jqassistant/cli/jqassistant-commandline-distribution/2.0.3/jqassistant-commandline-distribution-2.0.3-bin.zip. Note that the configuration mechanism is now completely based on .jqassistant.yml files, see https://jqassistant.github.io/jqassistant/doc/2.0.0/manual/#_configuration for details.

**Comment by JohT** [comment]
Thanks for your help @DirkMahler. Now I got nearly everything up and running. I only came across one thing that I have described in a separate issue: https://github.com/jQAssistant/jqa-java-plugin/issues/44
