### ISSUE TITLE
JavaEE integration

### ISSUE THREAD

**Issue by RickRainerLudwig** [buschmais/extended-objects#92]
Currently XO is not suitable to be handled in a transactional way within a JavaEE container, yet. This needs to be implemented to use XO in a JavaEE container in a concise way.

**Comment by Restage** [comment]
Hi Dirk,
thanks for your advice. Yes, I'm building a JSF application and your tip helped me a lot to get things running. But now I'm running into another issue with the too small transaction scope.

When I try to sort my JSF table with XO-Interface objects inside I get an 

```java
Warnung:   StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
com.buschmais.xo.api.XOException: Invalid access to an un-managed instance.
	at com.buschmais.xo.impl.proxy.InstanceInvocationHandler.invoke(InstanceInvocationHandler.java:21)
	at com.sun.proxy.$Proxy260.getSurname(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```
This issue also appears if I reload the website.

I know the feature is not yet implemented, but I was hopping for another idea of yours to work around this issue?!

The only idea I had is to wrap the XO Objects in a DTO, which is then used in my JSF components.

Best regards,
Richard
